### ISSUE TITLE
Tests fail with eigen 'unaligned array assert' on 32-bit (with GCC 5?)

### ISSUE THREAD

**Issue by AdamWill** [roboptim/roboptim-core#102]
Hi, folks. I've been working on updating the Fedora roboptim package to 3.1. I have it building, and on x86_64 builds the test suite passes 100% - but on i686 builds, 4 of the tests fail, all with approximately the same error:

    MatrixOrArrayOptions, 16>::plain_array() [with T = double; int Size = 2; int MatrixOrArrayOptions = 0]: Assertion `(reinterpret_cast<size_t>(eigen_unaligned_array_assert_workaround_gcc47(array)) & 0xf) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****"' failed.

which points to http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html . This seems to be a somewhat infamous issue in eigen circles, but not being a member of such rarefied company I can't make heads nor tails of it.

An affected build log can be found at https://kojipkgs.fedoraproject.org//work/tasks/2170/10502170/build.log for now, but it may disappear in a few weeks (scratch builds get garbage collected). The affected tests are 7 - cache, 13 - function-pool, 22 - ref, 41 - decorator-finite-difference-jacobian .

This is building on current Fedora Rawhide, where we have eigen 3.2.5 and GCC 5.1.1.

**Comment by AdamWill** [comment]
Building with `-DEIGEN_DONT_ALIGN` works around most of the failures, but one (which seems a bit different) remains:

    41: /builddir/build/BUILD/roboptim-core-3.1/tests/decorator-finite-difference-jacobian.cc(235): error in "finite_difference_jacobian<N8roboptim16EigenMatrixDenseE>": check output->match_pattern () failed. Mismatch at position 640

http://koji.fedoraproject.org/koji/watchlogs?taskID=10502815

**Comment by bchretien** [comment]
Hi Adam,

Thanks for packaging it for Fedora and reporting these issues, this is greatly appreciated. Most (if not all) of us use RobOptim on 64-bit systems, and Travis also runs on 64-bit VMs, so 32-bit support is clearly not as foolproof.

A typical problem is indeed Eigen's alignment for fixed-size vectors/matrices. We (nearly) always use dynamic-size containers (`vector_t`, `argument_t`, `jacobian_t`, `gradient_t` etc.), but we may still have some fixed-size containers in the tests. A quick check revealed:

* `cache`: [this](https://github.com/roboptim/roboptim-core/blob/master/tests/cache.cc#L75-L77) looks like the culprit, since `LRUCache` stores a `std::vector` of one of its template arguments (cf. [this](https://github.com/roboptim/roboptim-core/blob/master/include/roboptim/core/cache.hh#L62)), but an [Eigen::aligned_allocator](http://eigen.tuxfamily.org/dox-devel/group__TopicStlContainers.html) is not used for non-dynamic-size containers.
* `ref`: this looks like a [typo](https://github.com/roboptim/roboptim-core/blob/master/tests/ref.cc#L85) (second template argument should be `Unaligned`).
* `function-pool`: [j'accuse !](https://github.com/roboptim/roboptim-core/blob/master/tests/function-pool.cc#L51-L52)
* `decorator-finite-difference-jacobian`: this looks like numerical errors (a large part of our tests involves checking strings, which is likely to fail where numerical precision matters).

**Comment by bchretien** [comment]
If Fedora packaging scripts accept bundled patches (or if you have a 32-bit system/VM available), could you test 8b03203596548e36a41f02d7f48856d67e077da8 with the latest release to see if it solves the problem?

**Comment by AdamWill** [comment]
Indeed, with that all tests pass on an i686 build, thanks!

**Comment by bchretien** [comment]
Perfect! Closing this issue then.

**Comment by AdamWill** [comment]
Tests also pass on ARM, in case you were wondering :)

**Comment by bchretien** [comment]
That's good to know! Btw the Fedora package information needs to be updated (e.g. "Project Homepage" should be http://roboptim.net).

**Comment by AdamWill** [comment]
I already fixed that, but thanks :)
