### ISSUE TITLE
Tag variables with the group they belong to.

### ISSUE THREAD

**Issue by thomas-moulard** [roboptim/roboptim-core#21]
We would like, at least, to express the following spaces:

 * R
 * SE(n) / SO(n)

**Comment by bchretien** [comment]
This feature is currently being made available in RobOptim thanks to the [manifolds](https://github.com/stanislas-brossette/manifolds) and [roboptim-core-manifold](https://github.com/roboptim/roboptim-core-manifold) libraries. This is still under heavy development, and since this now concerns a new optional RobOptim extension, I'm closing this issue.
